### ISSUE TITLE
CodePath review

### ISSUE THREAD

**Issue by Vatyx** [Vatyx/flicks#1]
/cc @codepathreview

**Comment by codepathreview** [comment]
Hi @Vatyx , I cannot build your app because you import fonts directly from your computer so they cannot be found on mine.
<img width="526" alt="screen shot 2016-01-26 at 11 08 58 pm" src="https://cloud.githubusercontent.com/assets/7917093/12586189/defb2c4e-c481-11e5-96a2-422fe2297112.png">

Please fix it asap and let me know when you complete.

**Comment by Vatyx** [comment]
Sure thing. Do you know an easy way to fix this? I initially imported them
into the project.

**Comment by codepathreview** [comment]
Hmm..., I guess you put your fonts in `Downloads` folder and you didn't commit these files. It's quite complicated to import fonts to iOS project. You have to declare your fonts in `Info.plist`. So the easiest way to fix this issue is using default fonts in the system (you can find many different fonts in `Interface Builder`) instead of external fonts.

**Comment by Vatyx** [comment]
I changed the fonts and hopefully it should work now.

**Comment by codepathreview** [comment]
:+1: Nice work! The point of this homework was to get a chance to implement a TableView (one of the most common views in iOS) and to work with real data over the network (in this case from the Movies Database API).

A key part of these projects is that you add additional features and tweak the UI / UX because that will provide the most learning opportunities. We encourage you to complete the projects early each week with the required stories and then spend time adding your own UI elements and experimenting with optional extensions that will improve the user experience.

### Some small comments:
- At the beginning, I still cannot build your project. You should remove all external fonts when you don't use them anymore. I have to delete all the `red files` in your project navigator to build your app.
  <img width="253" alt="screen shot 2016-01-28 at 11 46 40 am" src="https://cloud.githubusercontent.com/assets/7917093/12637773/6f7526d2-c5ca-11e5-8718-43b4e089cc6c.png">
- Please be sure to follow the Swift code styling conventions for the homework .
  - Here is the useful guide: [Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide)
- Your app is very impressive! Good job :star2: 
- Well done when using `if let` to unwrap variables :+1: 
- You can initialize `movies` when declare like this `var movies = [NSDictionary]()` so you can use it anywhere without unwrapping. By this way, the function `numberOfItemsInSection` will be simpler, just use `return movies.count`.
- For now, the long movie title is truncated.

<img width="315" alt="screen shot 2016-01-28 at 2 13 47 pm" src="https://cloud.githubusercontent.com/assets/7917093/12637627/64145ef8-c5c9-11e5-8884-e1da00f97da2.png">

To avoid this, you can set `0` for the number of lines of this `UILabel` in order to display multiple lines.
<img width="605" alt="screen shot 2016-01-28 at 2 14 18 pm" src="https://cloud.githubusercontent.com/assets/7917093/12637643/7a75b160-c5c9-11e5-82f9-335948ca7dcc.png">
- Great idea when displaying the movie's details with similar movies :boom:
- But the app crashes when I tap `Ride along 2` movie.
- Nice to use `UITextView` to display `overview`, but for now, I can edit this field.
  <img width="317" alt="screen shot 2016-01-28 at 2 18 41 pm" src="https://cloud.githubusercontent.com/assets/7917093/12637744/3cc315b4-c5ca-11e5-8034-016993fa3670.png">
- You can declare the `apiKey` after `import` code (outside the class `MoviesViewController`), so you can use this constant everywhere in your app, even in other files.

Excellent submission overal :horse_racing: 

We have a detailed [Project 1 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_1_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
